# Use Node.js 18 as the Docker image
image: node:18

# Define the stages of the pipeline
stages:
  - test

test:
  stage: test
  image: node:18
  before_script:
    - npm install
  script:
    - npm test 
  artifacts:
    when: always
    reports:
      junit: jest-junit.xml
    paths:
      - jest-junit.xml
    expire_in: 1 week
