# Use Node.js 18 as the Docker image
image: node:18

# Define the stages of the pipeline
stages:
  - test

# Job for running tests
run_tests:
  stage: test
  script:
    - npm install
    - npx jest --reporters=default --reporters=jest-junit
  artifacts:
    when: always
    reports:
      junit:
        - junit.xml
  cache:
    paths:
      - node_modules/
