# Template for node see:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Nodejs.gitlab-ci.yml
# Coverage see:
# https://gist.github.com/rishitells/3c4536131819cff4eba2c8ab5bbb4570

image: node:18

stages:
  - test

javascript:
  stage: test
  script:
    - if [ ! -f "libssl1.1_1.1.1f-1ubuntu2_amd64.deb" ]; then wget -q http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb; fi 
        -dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb
    - npm ci
#   - npm run build -- we use ts-jest, no need for compilation
    - npm test
  artifacts:
    reports:
      junit:
        - junit.xml