# Dieses Docker-Image beinhaltet eine spezifische Version von Node.js
image: node:16

# Definiert die verschiedenen Stages der Pipeline
stages:
  - build
  - test

# Definiert den Cache für node_modules, um die Installation zu beschleunigen
cache:
  paths:
    - node_modules/

# Job zum Bauen des Projekts
build_project:
  stage: build
  script:
    - npm run build
  dependencies:
    - install_dependencies
  artifacts:
    paths:
      - build/

# Job zum Ausführen von Tests
run_tests:
  stage: test
  script:
    - npm test
  dependencies:
    - install_dependencies
  artifacts:
    when: always
    reports:
      junit:
        - report.xml
